name: Python Script Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0   * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies, add them in requirements.txt

    - name: Run Python script
      run: python main.py
